// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class PACIENTECITATest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void pACIENTECITA() {
    driver.get("http://18.221.191.106:8080/");
    driver.manage().window().setSize(new Dimension(1720, 934));
    driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
    driver.findElement(By.linkText("Agendar Cita")).click();
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.id("IdPaciente")).click();
    driver.findElement(By.id("IdPaciente")).sendKeys("1");
    driver.findElement(By.id("IdSchedule")).click();
    driver.findElement(By.id("IdSchedule")).sendKeys("2");
    driver.findElement(By.cssSelector(".form-group > .btn-primary")).click();
    assertThat(driver.switchTo().alert().getText(), is("Cita agregado"));
  }
}
